apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: dbit7n0ojntpd7
  POSTGRES_USER: uxbuvhokbbocan
  POSTGRES_PASSWORD: 826a1d23fbb6b89baadb9e23d44d3f408b7ab17c513ce2b6cf1e2d5cae1bd1a8