# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run ci
    - run: npm run lint
    - run: npm run test
      env: 
        AWS_ACCESS_KEY_ID: AKIAI634W2AOFL7Q3EPA
        AWS_SECRET_ACCESS_KEY: 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
        DATABASE_URL: postgres://uxbuvhokbbocan:826a1d23fbb6b89baadb9e23d44d3f408b7ab17c513ce2b6cf1e2d5cae1bd1a8@ec2-54-246-90-10.eu-west-1.compute.amazonaws.com:5432/dbit7n0ojntpd7
        JWT_SECRET: secret
    - run: npm run build    
